### ISSUE TITLE
网站修改密码后，app提示出错停止运行

### ISSUE THREAD

**Issue by aflyhorse** [zubinxiong/BangumiTV#6]
在班固米上改密后，点开任何番剧，因为抓取用户标记信息失败，都会提示出错停止运行（Exception啦！
登出，重新登陆后，恢复正常。

**Comment by zubinxiong** [comment]
不好意思，这么久才回复你。请问一下你使用的版本是什么？我在1.3.2 版本重复你的操作之后app 只会提示 timeout，并没有说停止运行。重新清除数据就好了

**Comment by aflyhorse** [comment]
GooglePlay上的 1.2 (bgm38)
看来需要更新开发版了

**Comment by zubinxiong** [comment]
因为Google play 上一直不通过审核（未经授权的图片），所以 1.2 之后的版本都只发了国内的酷市场和应用宝。多谢你的反馈，我最近会再尝试一下上架Google play的

**Comment by aflyhorse** [comment]
你是指那个封面图标吗……也可以试试看找赛老板拿授权，或者土法改造一下……

**Comment by zubinxiong** [comment]
各种番剧封面的图片被Google play 说没有版权，如果实在不行，考虑之后上架一个去除掉每日放松的版本

**Comment by aflyhorse** [comment]
可以辩解是合理使用嘛，我看豆瓣和比如imdb的app，肯定也不会有番剧电影封面版权啊……

**Comment by aflyhorse** [comment]
更换成1.3.2，重复操作后，并没有闪退情况，此问题单关闭。
