### ISSUE TITLE
只有超展开和搜索能用，其他都加载不出来

### ISSUE THREAD

**Issue by Hitagi-Hu** [zubinxiong/BangumiTV#7]

**Comment by zubinxiong** [comment]
之前通过抓取网页的形式获取的内容，现在网页更新了就挂了。现在正在重构，大概这周？我会先更新一个能重新用的版本

**Comment by zubinxiong** [comment]
感谢回复，上面的bug 已经修复了，在酷市场更新了1.3.3，可以去更新一下，感谢。[点这里去更新](https://www.coolapk.com/apk/me.ewriter.bangumitv)

**Comment by Hitagi-Hu** [comment]
我的进度还是不能浏览？

**Comment by zubinxiong** [comment]
清除一下数据重新登陆应该就行了

**Comment by Hitagi-Hu** [comment]
是的，可以了，非常感谢(+_+)
